"use client";

import Link from "next/link";
import Logo from "@/components/Logo";
import { useState } from "react";
import { ArrowRight, ArrowLeft, ArrowUpRight, Check, ChevronDown, Compass, GraduationCap, Leaf, LoaderCircle, RotateCcw, ShieldCheck, Sparkles, X } from "lucide-react";
import SyllabusUpload, { type Draft } from "./SyllabusUpload";
import { baseProfile, persona } from "./_lib/profile";
import type { CampusKey, Course, Day, LearningKey, Profile, Result } from "./_lib/types";

const steps = ["기본 정보", "나의 진로", "학습 성향", "시간표 선호", "대학생활 계획", "Campus Life"];
const careers = ["Embedded Software", "Backend", "Frontend", "AI/ML", "Data", "Game", "System Software", "Graduate School", "아직 모름", "직접 입력"];
const days: Day[] = ["월", "화", "수", "목", "금", "토", "일"];
const learningLabels: [LearningKey, string, string][] = [
  ["memorization", "암기", "개념과 내용을 기억하는 공부"], ["problem_solving", "문제 해결", "생각하고 답을 찾아가는 공부"],
  ["practice", "실습", "직접 만들고 실행하며 배우기"], ["project", "프로젝트", "하나의 결과물을 완성하는 수업"],
  ["team_project", "팀 프로젝트", "함께 역할을 나누어 진행하기"], ["presentation", "발표", "사람들 앞에서 생각 전달하기"],
  ["essay", "서술형 평가", "글로 논리와 생각을 설명하기"], ["exam", "시험 중심 평가", "과제보다 시험 비중이 높은 수업"],
];
const campusLabels: [CampusKey, string, string][] = [["social", "새로운 사람 만나기", "다양한 학생과 교류하고 싶어요"], ["discussion", "토론과 참여", "의견을 나누며 배우고 싶어요"], ["exploration", "새로운 분야 경험", "전공 밖의 세계도 탐색하고 싶어요"], ["quiet", "조용한 개인 학습", "혼자 집중하는 시간이 좋아요"]];
const partLabels = { career: "진로", learning: "학습", assessment: "평가", schedule: "시간표", campus: "대학생활", academic: "학업계획" };
function time(minutes: number) { return `${Math.floor(minutes / 60).toString().padStart(2, "0")}:${(minutes % 60).toString().padStart(2, "0")}`; }
function schedule(course: Course) { return course.schedule.map(m => `${m.day} ${time(m.start)}–${time(m.end)}`).join(" · "); }
function Preference({ label, description, value, onChange }: { label: string; description: string; value: number; onChange: (v: number) => void }) {
  return <fieldset className="preference-field"><legend>{label}</legend><p>{description}</p><div className="preference-options">{[[0,"싫어요"],[50,"모르겠어요"],[100,"좋아요"]].map(([n,text])=><label key={n}><input type="radio" name={label} checked={value===n} onChange={()=>onChange(Number(n))}/><span>{text}</span></label>)}</div></fieldset>;
}
function Chips({ label, selected, onChange }: { label: string; selected: Day[]; onChange: (v: Day[]) => void }) {
  return <div className="day-field"><h3>{label}</h3><div className="day-chips">{days.map(day => <button type="button" className={selected.includes(day) ? "day active" : "day"} key={day} aria-pressed={selected.includes(day)} onClick={() => onChange(selected.includes(day) ? selected.filter(x => x !== day) : [...selected, day])}>{day}<small>요일</small></button>)}</div></div>;
}

export default function Home() {
  const [view, setView] = useState<"landing" | "profile" | "result">("landing");
  const [step, setStep] = useState(0);
  const [profile, setProfile] = useState<Profile>(structuredClone(baseProfile));
  const [syllabusDrafts, setSyllabusDrafts] = useState<Draft[]>([]);
  const [uploadedCourses, setUploadedCourses] = useState<Course[]>([]);
  const [maxCredits, setMaxCredits] = useState(String(baseProfile.max_credits));
  const [customCareer, setCustomCareer] = useState("");
  const [uploading, setUploading] = useState(false);
  const [result, setResult] = useState<Result | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  function update<K extends keyof Profile>(key: K, value: Profile[K]) { setProfile(p => ({ ...p, [key]: value })); }
  function start(kind?: "A" | "B") {
    if (kind) { const next = persona(kind); setProfile(next); setMaxCredits(String(next.max_credits)); setUploadedCourses([]); setSyllabusDrafts([]); setCustomCareer(""); }
    setView("profile"); setStep(0); setError(""); setNotice("");
  }
  async function requestRecommendations(failedCourse?: string, successfulOverride?: string[]) {
    if (busy || uploading) return;
    if (syllabusDrafts.length) { setError("아직 선택하지 않은 과목이 있어요. 원하는 과목의 ‘꼭 듣고 싶은 과목’을 누르거나 ‘선택 없이 다음으로’를 눌러 주세요."); setStep(4); setView("profile"); return; }
    if (!/^\d+$/.test(maxCredits) || Number(maxCredits)<1 || Number(maxCredits)>24) { setError("최대 신청학점은 1~24 사이의 정수로 입력해 주세요."); setStep(3); setView("profile"); return; }
    if (profile.careers.includes("직접 입력") && !customCareer.trim()) { setError("직접 입력한 진로를 작성해 주세요."); setStep(1); setView("profile"); return; }
    setBusy(true); setError(""); setNotice("");
    const recovery = Boolean(failedCourse || successfulOverride);
    const body = { profile: {...profile, careers: [...new Set(profile.careers.map(c=>c==="직접 입력"?customCareer.trim():c))], max_credits: Number(maxCredits)}, custom_courses: uploadedCourses, successful_ids: successfulOverride ?? (recovery ? result?.successful_ids ?? [] : []), failed_ids: recovery ? result?.failed_ids ?? [] : [], current_ids: recovery ? result?.recommendations.map(r => r.course.course_id) ?? [] : [], ...(failedCourse ? { failed_course_id: failedCourse } : {}) };
    try {
      const response = await fetch(failedCourse ? "/course-plan/api/recommend/alternative" : "/course-plan/api/recommend", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body), signal: AbortSignal.timeout(60_000) });
      const data = await response.json();
      if (!response.ok) throw new Error(typeof data.detail === "string" ? data.detail : "입력값을 확인해 주세요. 학점과 학년 등 허용 범위를 벗어났습니다.");
      setResult(data); setView("result");
      if (failedCourse) setNotice("실패한 과목을 제외하고 시간표를 다시 구성했습니다. 수강 성공 과목은 유지됩니다.");
      else if (successfulOverride) setNotice("수강 상태를 반영했습니다.");
      window.scrollTo({ top: 0, behavior: "smooth" });
    } catch (e) { setError(e instanceof Error ? e.message : "추천 요청에 실패했습니다."); }
    finally { setBusy(false); }
  }
  function toggleCareer(career: string) {
    setProfile(p=>({...p, careers: p.careers.includes(career) ? p.careers.filter(c=>c!==career) : career==="아직 모름" ? [career] : [...p.careers.filter(c=>c!=="아직 모름"),career].slice(0,3)}));
  }

  return <div className="site">
    <header className="sticky top-0 z-20 border-b border-line/70 bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-3.5"><div className="flex items-center gap-2"><Logo /><button type="button" className="text-sm text-muted hover:text-brand-navy" onClick={() => { setView("landing"); setError(""); }}>· 수강신청 도우미</button></div><Link href="/" className="rounded-full bg-brand-navy px-4 py-2 text-sm font-medium text-white transition hover:bg-brand-deep">← 전체 서비스</Link></div></header>
    <main>
      {view === "landing" && <>
        <section className="relative overflow-hidden bg-[#f4f6f8]"><div className="pointer-events-none absolute -left-32 -top-32 h-96 w-96 rounded-full bg-brand-sky/30 blur-3xl" /><div className="pointer-events-none absolute -bottom-40 -right-24 h-[28rem] w-[28rem] rounded-full bg-brand-sky/40 blur-3xl" /><div className="relative mx-auto grid max-w-6xl items-center gap-10 px-5 py-20 sm:py-24 lg:grid-cols-[1.05fr_1fr]"><div className="flex flex-col items-start gap-6"><div className="flex w-fit overflow-hidden rounded-full text-xs font-medium sm:text-sm"><span className="relative z-10 rounded-full bg-brand-sky px-4 py-1.5 text-white">02</span><span className="-ml-3 rounded-r-full bg-brand-navy py-1.5 pl-6 pr-4 text-white">수강신청·학사 일정 도우미</span></div><h1 className="text-4xl font-bold leading-[1.25] text-brand-ink sm:text-[54px]">좋은 강의 말고,<br /><span className="text-brand-bright">나에게 좋은 강의.</span></h1><p className="max-w-xl text-base text-muted sm:text-lg">너의 진로, 공부 스타일, 그리고 대학생활까지.<br />이번 학기는 남들의 추천 대신 나만의 기준으로 골라봐.</p><div className="flex flex-col items-start gap-3"><button type="button" className="flex items-center gap-3 rounded-full bg-brand-navy px-7 py-4 text-[15px] font-bold text-white shadow-lg shadow-brand-navy/20 hover:bg-brand-deep" onClick={() => start()}><span className="text-[15px] font-bold">내 수강전략 만들기</span> <ArrowUpRight size={18} /></button><p className="text-xs text-muted">로그인 없이 시작 · 약 3분이면 충분해요</p></div><div className="flex flex-wrap gap-2 text-xs font-medium text-brand-navy"><span className="flex items-center gap-1.5 rounded-full bg-white px-3.5 py-2"><ShieldCheck size={15} /> 시간 충돌 자동 확인</span><span className="flex items-center gap-1.5 rounded-full bg-white px-3.5 py-2"><RotateCcw size={15} /> 수강 실패에도 Plan B</span></div></div>
          <div className="hero-art" aria-label="개인화 수강전략 예시"><div className="art-orbit orbit-one" /><div className="art-orbit orbit-two" /><span className="floating-tag tag-top"><Compass size={17} /> Embedded Software</span><span className="floating-tag tag-bottom"><Leaf size={17} /> 금요일은 나를 위한 시간</span><div className="strategy-preview"><div className="preview-top"><span><Sparkles size={15} /> MY SEMESTER</span><span className="preview-dots">•••</span></div><div className="preview-heading"><span className="preview-icon"><GraduationCap size={30} /></span><div><small>나의 수강전략</small><h2>이런 학기, 어때요?</h2></div></div><div className="preview-course"><div><span className="tiny-label">전공선택</span><h3>시스템프로그래밍</h3><p>실습과 문제 해결이 좋은 너에게</p></div><div className="preview-score">94<small>FIT SCORE</small></div></div><div className="preview-bars">{[76,94,87].map((n,i)=><div key={n}><span>{["진로 적합도","학습성향","시간표"][i]}</span><div><i style={{width:`${n}%`}} /></div><b>{n}</b></div>)}</div><div className="preview-plan"><span>PLAN B</span><div><strong>C++ Programming</strong><small>다음 선택도 준비되어 있어요</small></div><ArrowRight size={18} /></div><div className="preview-footer"><Check size={14} /> 시간 충돌 없이, 나에게 맞게.</div></div><span className="art-label">예시 화면 · 가상 적합도</span></div>
        </div></section>
        <section className="mx-auto max-w-6xl px-5 py-20"><div className="flex flex-col gap-5"><div className="flex w-fit overflow-hidden rounded-full text-xs font-medium sm:text-sm"><span className="relative z-10 rounded-full bg-brand-sky px-4 py-1.5 text-white">특징</span><span className="-ml-3 rounded-r-full bg-brand-navy py-1.5 pl-6 pr-4 text-white">이렇게 골라 드려요</span></div><h2 className="text-3xl font-bold leading-tight text-brand-ink sm:text-4xl">나다운 학기를 만드는 세 가지 기준</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3"><div className="flex gap-5 rounded-2xl border border-line bg-white p-6"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-r-full bg-brand-navy text-sm font-bold text-white">01</span><div className="flex flex-col gap-1.5"><span className="text-[11px] font-bold tracking-wider text-brand-bright">FIND YOUR FIT</span><h3 className="font-bold text-brand-ink">공부 스타일도 취향이니까</h3><p className="text-sm text-muted">암기보다 실습, 팀플보다 개인과제. 내가 편한 방식으로 배워요.</p></div></div><div className="flex gap-5 rounded-2xl border border-line bg-white p-6"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-r-full bg-brand-navy text-sm font-bold text-white">02</span><div className="flex flex-col gap-1.5"><span className="text-[11px] font-bold tracking-wider text-brand-bright">MAKE IT POSSIBLE</span><h3 className="font-bold text-brand-ink">원하는 일상까지 담아서</h3><p className="text-sm text-muted">진로에 가까워지는 수업과 지키고 싶은 공강을 함께 고려해요.</p></div></div><div className="flex gap-5 rounded-2xl border border-line bg-white p-6"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-r-full bg-brand-navy text-sm font-bold text-white">03</span><div className="flex flex-col gap-1.5"><span className="text-[11px] font-bold tracking-wider text-brand-bright">ALWAYS HAVE A PLAN B</span><h3 className="font-bold text-brand-ink">수강 실패가 끝은 아니니까</h3><p className="text-sm text-muted">한 과목을 놓쳐도 괜찮아요. 조건에 맞는 다음 선택을 찾아줘요.</p></div></div></div></section>
        <section className="px-5 pb-24"><div className="relative mx-auto flex max-w-6xl flex-col items-start justify-between gap-6 overflow-hidden rounded-3xl bg-gradient-to-r from-brand-navy to-brand-bright px-8 py-12 text-white sm:px-12 md:flex-row md:items-center"><div className="absolute -left-10 top-1/2 h-40 w-20 -translate-y-1/2 rounded-r-full bg-white/10" /><div className="absolute -right-6 top-1/2 h-56 w-28 -translate-y-1/2 rounded-r-full bg-brand-sky/30" /><div className="relative flex flex-col gap-2"><span className="text-xs font-bold tracking-widest text-brand-sky">QUICK PREVIEW</span><h3 className="text-2xl font-bold">어떤 추천이 나오는지 궁금하다면?</h3><p className="text-white/75">두 가지 예시 프로필로 빠르게 시작해 보세요.</p></div><div className="relative flex flex-wrap gap-3"><button type="button" className="flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-brand-navy transition hover:bg-brand-sky hover:text-white" onClick={() => start("A")}><span className="font-bold">A. 임베디드 개발자</span> <ArrowRight size={16} /></button><button type="button" className="flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-brand-navy transition hover:bg-brand-sky hover:text-white" onClick={() => start("B")}><span className="font-bold">B. 진로 탐색 새내기</span> <ArrowRight size={16} /></button></div></div></section>
      </>}

      {view === "profile" && <section className="workspace"><aside className="step-sidebar"><span className="eyebrow">BUILD YOUR SEMESTER</span><h1>너를 알아가는<br />여섯 가지 질문.</h1><p>정답은 없어요.<br />지금의 나를 알려주세요.</p><nav aria-label="프로필 단계">{steps.map((label,i)=><button key={label} className={`step-link ${step===i?"current":""} ${step>i?"done":""}`} disabled={uploading} onClick={()=>setStep(i)} aria-current={step===i?"step":undefined}><span>{step>i?<Check size={14}/>:String(i+1).padStart(2,"0")}</span>{label}</button>)}</nav><div className="sidebar-note"><ShieldCheck size={19}/><p>추천은 입력한 선호로 계산해요.<br />MBTI·성별로 능력을 추정하지 않아요.</p></div></aside>
        <div className="form-panel"><div className="form-top"><span>PROFILE / {String(step+1).padStart(2,"0")}</span><span>{step+1} of 6</span></div><div className="progress-track"><i style={{width:`${(step+1)/6*100}%`}}/></div><form onSubmit={e=>{e.preventDefault();if(step<5)setStep(step+1);else void requestRecommendations();}}>
          <div className="form-heading"><h2>{["반가워요! 기본부터 시작해요.","어떤 미래를 그리고 있나요?","어떤 공부가 나에게 맞나요?","이번 학기, 언제 만나볼까요?","앞으로의 계획을 알려주세요.","수업 밖의 나도 중요하니까."][step]}</h2><p>{["현재 학업 단계와 기본 정보를 알려주세요.","진로가 정해지지 않았어도 괜찮아요.","싫어요, 모르겠어요, 좋아요 중 골라주세요.","공강일은 반드시 지키고, 나머지 선호는 적합도에 반영해요.","병역 계획은 기초 과목의 학업계획 적합도에 반영해요.","대학생활에서 중요하게 생각하는 경험을 골라주세요."][step]}</p></div>
          {step===0 && <><div className="field-grid"><label>학교<input value={profile.school} maxLength={100} onChange={e=>update("school",e.target.value)}/></label><label>학과 / 전공<input value={profile.major} maxLength={100} onChange={e=>update("major",e.target.value)}/></label><label>학년<select value={profile.year} onChange={e=>update("year",Number(e.target.value))}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n}학년</option>)}</select></label><label>학기<select value={profile.semester} onChange={e=>update("semester",Number(e.target.value))}><option value={1}>1학기</option><option value={2}>2학기</option></select></label><label>이수학점<input type="number" min={0} max={300} required value={profile.earned_credits} onChange={e=>update("earned_credits",Number(e.target.value))}/></label><label>GPA / 4.5<input type="number" min={0} max={4.5} step={0.01} required value={profile.gpa} onChange={e=>update("gpa",Number(e.target.value))}/></label></div><div className="field-grid"><label>MBTI (선택)<select value={profile.mbti} onChange={e=>update("mbti",e.target.value)}><option value="">선택 안 함</option>{["ISTJ","ISFJ","INFJ","INTJ","ISTP","ISFP","INFP","INTP","ESTP","ESFP","ENFP","ENTP","ESTJ","ESFJ","ENFJ","ENTJ"].map(m=><option key={m} value={m}>{m}</option>)}</select></label><label>성별 (선택)<select value={profile.gender} onChange={e=>update("gender",e.target.value)}><option value="">선택 안 함</option><option value="남">남</option><option value="여">여</option></select></label></div><p className="field-note">MBTI와 성별은 추천 점수에 사용하지 않습니다.</p></>}
          {step===1 && <><p className="field-note">최대 3개까지 선택할 수 있어요. ({profile.careers.length}/3)</p><div className="career-grid">{careers.map(c=>{const selected=profile.careers.includes(c);return <button type="button" key={c} aria-pressed={selected} disabled={!selected&&c!=="아직 모름"&&profile.careers.length>=3} className={selected?"career-card selected":"career-card"} onClick={()=>toggleCareer(c)}><GraduationCap size={18}/><span>{c}</span>{selected&&<Check size={15}/>}</button>;})}</div>{profile.careers.includes("직접 입력")&&<label className="full-field">희망 진로<input maxLength={100} required value={customCareer} onChange={e=>setCustomCareer(e.target.value)} placeholder="예: 보안 엔지니어"/></label>}</>}
          {step===2 && <div className="range-grid">{learningLabels.map(([key,label,description])=><Preference key={key} label={label} description={description} value={profile.learning[key]} onChange={v=>update("learning",{...profile.learning,[key]:v})}/>)}</div>}
          {step===3 && <><Chips label="꼭 지키고 싶은 공강일" selected={profile.free_days} onChange={v=>update("free_days",v)}/><Chips label="선호하는 등교일" selected={profile.preferred_days} onChange={v=>update("preferred_days",v)}/><div className="field-grid"><label>수업 시간대<select value={profile.time_preference} onChange={e=>update("time_preference",e.target.value as Profile["time_preference"])}><option value="any">상관없어요</option><option value="morning">오전 수업</option><option value="afternoon">오후 수업</option></select></label><label>최대 신청학점<input type="number" required min={1} max={24} value={maxCredits} onChange={e=>setMaxCredits(e.target.value)}/></label></div><label className="toggle-row"><span><strong>가능하면 몰아 듣기</strong><small>등교일이 늘지 않는 조합을 우선해요</small></span><input type="checkbox" checked={profile.compact_days} onChange={e=>update("compact_days",e.target.checked)}/></label></>}
          {step===4 && <><label className="full-field">병역 계획<select value={profile.military_status} onChange={e=>update("military_status",e.target.value as Profile["military_status"])}><option value="none">해당 없음</option><option value="completed">군필</option><option value="planned">미필 / 계획 있음</option><option value="undecided">미필 / 계획 미정</option></select></label>{profile.military_status==="planned"&&<div className="field-grid"><label>예상 복무 시작<input maxLength={40} value={profile.service_start} onChange={e=>update("service_start",e.target.value)} placeholder="예: 다음 학년 1학기"/></label><label>복무기간 (개월)<input type="number" required min={1} max={36} value={profile.service_months} onChange={e=>update("service_months",Number(e.target.value))}/></label><label>예상 복학 시점<input maxLength={40} value={profile.return_term} onChange={e=>update("return_term",e.target.value)} placeholder="예: 복무 후 2학기"/></label></div>}<div className="info-box"><Leaf size={19}/><p>이번 MVP는 복무 계획이 있으면 기초 과목에 학업계획 가점을 줍니다. 복무 전후 학기별 로드맵은 후속 기능입니다.</p></div><SyllabusUpload drafts={syllabusDrafts} setDrafts={setSyllabusDrafts} courses={uploadedCourses} onChange={next=>{setUploadedCourses(next);update("required_ids",next.map(c=>c.course_id));}} onBusy={setUploading}/ ><p className="field-note">꼭 듣고 싶은 과목은 선택 사항입니다. 선택 없이 진행하면 업로드한 과목을 추천에 반영하지 않습니다.</p><button type="button" className="secondary" disabled={uploading} onClick={()=>{setSyllabusDrafts([]);setUploadedCourses([]);update("required_ids",[]);setError("");setStep(5);}}>선택 없이 다음으로</button></>}
          {step===5 && <><div className="range-grid">{campusLabels.map(([key,label,desc])=><Preference key={key} label={label} description={desc} value={profile.campus[key]} onChange={v=>update("campus",{...profile.campus,[key]:v})}/>)}</div><div className="info-box"><Sparkles size={19}/><p>준비됐어요! 진로와 학습성향에 맞는 과목을 찾고, 수강 실패에 대비한 다음 선택까지 확인해 보세요.</p></div></>}
          {error&&<div role="alert" className="error-box">{error}</div>}<div className="form-bottom"><button type="button" className="text-button" disabled={uploading} onClick={()=>step>0?setStep(step-1):setView("landing")}><ArrowLeft size={16}/>{step>0?"이전 질문":"홈으로"}</button><button className="primary" type="submit" disabled={busy||uploading}>{busy?<><LoaderCircle className="spin" size={17}/>수강전략 계산 중</>:step<5?<>다음 질문 <ArrowRight size={17}/></>:<>내 추천 확인하기 <Sparkles size={17}/></>}</button></div>
        </form></div>
      </section>}

      {view==="result"&&result&&<section className="results"><div className="result-heading"><div><span className="eyebrow"><Sparkles size={14}/> YOUR SEMESTER STRATEGY</span><h1>이번 학기, 너의 다음 선택.</h1><p>{!profile.careers.length||profile.careers.includes("아직 모름")?"새로운 가능성을 탐색하는":profile.careers.map(c=>c==="직접 입력"?customCareer:c).join(" · ")+"에 가까워지는"} 수강전략을 준비했어요.</p></div><button className="secondary" disabled={busy} onClick={()=>{setView("profile");setStep(0);setError("");}}>프로필 수정 <ArrowUpRight size={16}/></button></div>
        <div className="summary-row"><div><small>추천 과목</small><strong>{result.recommendations.length}<span>개</span></strong></div><div><small>총 신청학점</small><strong>{result.total_credits}<span>/ {result.max_credits}학점</span></strong></div><div><small>나를 위한 공강</small><strong className="free-summary">{result.free_days.length?result.free_days.join(" · "):"없음"}<span>{result.free_days.length?"요일":""}</span></strong></div><div className="summary-check"><ShieldCheck size={25}/><span>시간 충돌 · 학점 제한<br/><strong>검증 완료</strong></span></div></div>
        <div className="result-meta"><span><span className="status-dot"/> {result.explanation_mode==="template"?"계산 근거 기반 설명":"AI가 선택한 계산 근거 기반 설명"}</span><span>기본 가상 과목 + 확인한 수업계획서 · 실제 수강 가능 여부는 학교에서 확인하세요</span></div>
        {notice&&<div role="status" className="notice-box"><Check size={17}/>{notice}</div>}{error&&<div role="alert" className="error-box">{error}</div>}{result.warnings.map(w=><div className="warning-box" key={w}>{w}</div>)}
        {busy&&<div className="busy-banner" role="status"><LoaderCircle className="spin" size={18}/>조건을 다시 확인하고 있어요…</div>}
        <div className="recommendation-grid">{result.recommendations.map((row,index)=><article className={`recommendation-card ${row.status==="success"?"registered":""}`} key={row.course.course_id} data-testid="course-card"><div className="card-top"><span className="course-category">{row.course.category} · {row.course.credits}학점</span><span className="course-order">{row.status==="success"?<><Check size={14}/> 수강 성공</>:String(index+1).padStart(2,"0")}</span></div><div className="course-title-row"><div><h2>{row.course.name}</h2><p>{schedule(row.course)} · {row.course.professor}</p></div><div className="fit-score">{row.score.total}<small>FIT SCORE</small></div></div><div className="score-grid">{Object.entries(row.score.parts).map(([key,value])=><div key={key}><span>{partLabels[key as keyof typeof partLabels]}</span><b>{value}</b><i><em style={{width:`${value}%`}}/></i></div>)}</div><div className="reason"><Sparkles size={15}/><p>{row.reason}</p></div><details className="course-details"><summary>수업 및 평가 정보 <ChevronDown size={14}/></summary><p>{row.course.syllabus}</p>{row.course.course_id.startsWith("upload-")?<p>평가 비중·성향 정보 미확인: 적합도 계산에 중립값을 사용합니다.</p>:<p>시험 {row.course.assessment.exam}% · 과제 {row.course.assessment.assignment}% · 프로젝트 {row.course.assessment.project}%</p>}</details><div className="alternatives"><span className="alt-heading">NEXT CHOICES <small>전체 시간표 기준 개별 대체 후보</small></span>{row.alternatives.length?row.alternatives.map((alt,i)=><div className="alternative-row" key={alt.course.course_id}><span className="plan-label">PLAN {String.fromCharCode(66+i)}</span><div><strong>{alt.course.name}</strong><small>{schedule(alt.course)} · {alt.course.credits}학점</small></div><b>{alt.score.total}</b></div>):<p className="empty-alternatives">{row.alternative_notice}</p>}</div><div className="registration-actions"><button disabled={busy} className={row.status==="success"?"success-button active":"success-button"} onClick={()=>void requestRecommendations(undefined,row.status==="success"?result.successful_ids.filter(id=>id!==row.course.course_id):[...result.successful_ids,row.course.course_id])}><Check size={15}/>{row.status==="success"?"성공 해제":"수강 성공"}</button><button className="fail-button" disabled={busy||row.status==="success"} onClick={()=>void requestRecommendations(row.course.course_id)}><X size={15}/>수강 실패 → 재추천</button></div></article>)}</div>
        {!result.recommendations.length&&<div className="empty-state"><Compass size={32}/><h2>지금 조건에 맞는 과목이 없어요.</h2><p>공강일과 최대학점을 확인하고 프로필을 조정해 주세요.</p></div>}
        <details className="excluded-list"><summary>추천에서 제외된 과목과 이유 ({result.excluded.length}) <ChevronDown size={15}/></summary>{result.excluded.map(c=><div key={c.course_id}><span>{c.name}</span><span>{c.reason}</span></div>)}</details><div className="result-bottom"><p>점수는 진로 30% · 학습 25% · 평가 15% · 시간표 15% · 대학생활 10% · 학업계획 5%로 계산합니다.<br/>대체 후보는 한 과목씩 교체할 때 유효합니다. 실제 실패 시 전체 조합을 다시 검증합니다.</p><button className="secondary" disabled={busy} onClick={()=>void requestRecommendations()}>수강 상태 초기화 <RotateCcw size={15}/></button></div>
      </section>}
    </main><footer><div className="mx-auto flex max-w-6xl flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><Logo light /><p className="text-xs">나를 아는 선택이, 나다운 학기를 만든다.</p></div></footer>
  </div>;
}
